### PR TITLE
Add support for -p and -u command line arguments

### PR DESCRIPTION
**Pull request by lizlam**
Adding a couple of command line arguments to provide a little tighter integration with Custom Tools in P4V.

### CODE REVIEW

**Comment by lizlam** [comment]
@jbuddha Feel free to suggest improvements and I can update the pull request.

**Comment by jbuddha** [comment]
Apologies, I have been away.

**Comment by jbuddha** [comment]
Can you also update the Readme with your flags as well?

**Comment by lizlam** [comment]
@jbuddha Sure.

**Pull request merged**
